mylist=[]
mylist.append(1)
mylist.append(1)
mylist.append(44)
mylist.append(44)
mylist.append(44)
mylist.append(44)
mylist.append(44)
mylist.append(1)
mylist.append(5)
mylist.pop()
mylist.remove(1)
mylist.sort(reverse=True)
print(mylist)
mylist.sort()
print(mylist)
count = mylist.count(44)
print(count)

